After Travis failure; rebuilt book and try again
! Missing $ inserted.
<inserted text>
                $
l.5675

You may need to add $ $ around a certain inline R expression `r ` in RJafrocBook.Rmd. See https://github.com/rstudio/rmarkdown/issues/385 for more info.
Error: LaTeX failed to compile RJafrocBook.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJafrocBook.log for more info.

Followed instructions in https://yihui.org/tinytex/r/#debugging
Updated packages