Error in pdf build traced to missing years in some citations
! Package natbib Error: Bibliography not compatible with author-year citations.

Error: LaTeX failed to compile RJafrocBook.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJafrocBook.log for more info.
Execution halted

Exited with status 1.